atlas/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView
from django.views.static import serve
from django.conf import settings

admin.site.site_header = 'Atlas beheer'
admin.site.site_title = 'Atlas beheer'
admin.site.site_url = '/atlas'

urlpatterns = [
    path('atlas/admin/', admin.site.urls),
]

if settings.AUTHENTICATION_ENABLE_CREDENTIALS:
    urlpatterns += [
        path('atlas/accounts/', include('django.contrib.auth.urls'))
    ]

if settings.AUTHENTICATION_ENABLE_OIDC:
    urlpatterns += [
        path('atlas/oidc/', include('mozilla_django_oidc.urls'))
    ]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^atlas/media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

urlpatterns += [
    path('atlas/', include('homepage.urls'), name='homepage'),
    path('', RedirectView.as_view(url='/atlas/'))
]

homepage/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path, include
from rest_framework import routers
from homepage import views, viewclasses
from webservice import viewsets

app_name = 'homepage'

api_router = routers.DefaultRouter()
api_router.register(r'maps', viewsets.MapViewSet, basename='maps')
api_router.register(r'layers', viewsets.LayerViewSet, basename='layers')

urlpatterns = [
    path('help', views.v3_help, name='v3_help'),
    path('disclaimer', views.v3_disclaimer, name='v3_disclaimer'),
    path('login', viewclasses.LoginView.as_view(template_name='v3/login.html'), name='v3_login'),
    path('login/failure', views.v3_login_failure, name='v3_login_failure'),
    path('logout', auth_views.LogoutView.as_view(template_name='v3/logout.html'), name='v3_logout'),
    path('admin2/', views.v3_admin, name='v3_admin'),
    path('api/v1/token', views.v3_token, name='v3_token'),
    path('api/v1/', include(api_router.urls)),
    re_path('embed', views.embed, name='embed'),
    re_path(r'((?P<theme_slug>[a-z0-9\-]+)?)', views.v3, name='v3'),
]

homepage/views.py
import logging

from constance import config
from django.http import JsonResponse, HttpResponseNotFound
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse, redirect, render, get_object_or_404
from django.urls import reverse
from django.views.decorators.clickjacking import xframe_options_exempt

from utils.tools import is_ctrix
from webservice.models import Layer, Map, Viewer
from .lib import get_help_content


logger = logging.getLogger(__name__)
help_content = get_help_content()


@xframe_options_exempt
def embed(request):
    authorized_layers = Layer.authorized.user_or_group(request.user, is_ctrix(request))
    visible_layers = authorized_layers.filter(~Q(not_in_atlas=True))

    context = {
        'data': {
            'is_embed': True,
            'config': _get_config(request),
            'user': _get_user(request),
            'layers': _default_layers() + [ layer.to_dict() for layer in visible_layers ]
        }
    }

    return render(request, 'v3/app.html', context)

def v3(request, theme_slug=''):
    authorized_layers = Layer.authorized.user_or_group(request.user, is_ctrix(request))

    context = {}

    if theme_slug:
        theme = get_object_or_404(Map, slug=theme_slug)
        visible_layers = authorized_layers.filter(map=theme)
        context['title'] = theme.title
    else:
        visible_layers = authorized_layers.filter(~Q(not_in_atlas=True))

    context['data'] = {
        'is_embed': False,
        'config': _get_config(request),
        'user': _get_user(request),
        'layers': _default_layers() + [ layer.to_dict() for layer in visible_layers ]
    }

    return render(request, 'v3/app.html', context)

def v3_help(request):
    return render(request, 'v3/help.html', {
        'title': 'Help',
        'content': help_content
    })

def v3_disclaimer(request):
    if config.DISCLAIMER:
        return render(request, 'v3/disclaimer.html', {
            'title': 'Disclaimer',
            'content': config.DISCLAIMER,
        })

    return HttpResponseNotFound('Er is geen disclaimer aanwezig')

def v3_login(request):
    return render(request, 'v3/login.html', {
        'title': 'Login'
    })

def v3_login_failure(request):
    return render(request, 'v3/login_failure.html', {
        'title': 'Login mislukt'
    })

def v3_token(request):
    if request.user.is_authenticated:
        return JsonResponse({
            'token': request.session.get('oidc_access_token')
        })

    return HttpResponse('Unauthorized', status=401)

@login_required(login_url='admin:login')
def v3_admin(request):
    if not request.user.is_superuser:
        return redirect(reverse('admin:login'))

    authorized_layers = Layer.authorized.user_or_group(request.user, is_ctrix(request))
    visible_layers = authorized_layers.filter(~Q(not_in_atlas=True))

    context = {
        'data':  {
            'config': _get_config(request),
            'user': _get_user(request),
            'layers': _default_layers() + [ layer.to_dict() for layer in visible_layers ]
        }
    }

    return render(request, 'v3/admin.html', context)

def _default_layers():
    if Layer.objects.filter(is_base=True).count() > 0:
        # Do not return default base layers when the database contains base layers
        return []

    # TODO: Remove default hardcoded layers
    return [
        {
            'id': 'brt_topo_kaart_totaal',
            'title': 'Kaart grijs',
            'name': 'topp:topografische_kaart_grijs',
            'opacity': 0.9,
            'url': 'https://datalab.purmerend.nl/geoserver/topp/wms',
            'server_type': 'geoserver',
            'is_base': True,
            'is_visible': True,
            'metadata': {
                'description': 'Topografische achtergrondkaart',
                'organization': 'Gemeente Purmerend',
                'updated': '2020'
            }
        },
        {
            'id': 'purm_lufo2020',
            'title': 'Luchtfoto 2020',
            'name': 'topp:Lufo_Totaal_2020',
            'opacity': 0.9,
            'url': 'https://datalab.purmerend.nl/geoserver/topp/wms',
            'server_type': 'geoserver',
            'is_base': True,
            'is_visible': False,
            'metadata': {
                'description': 'Luchtfoto',
                'organization': 'Gemeente Purmerend',
                'updated': '2020'
            }
        },
    ]

def _get_config(request):
    return {
        'organization_name': config.ORGANIZATION_NAME,
        'position': {
            'zoom': config.POSITION_ZOOM,
            'center': {
                'x': config.POSITION_CENTER_X,
                'y': config.POSITION_CENTER_Y
            }
        },
        'suggest_municipalities': config.SUGGEST_MUNICIPALITIES,
        'show_disclaimer': config.DISCLAIMER != '',
        'viewers': [ viewer.to_dict() for viewer in Viewer.visible.for_request(request) ],
    }

def _get_user(request):
    user = request.user

    if not user.is_authenticated:
        return None

    return {
        'id': user.id,
        'username': user.username,
        'first_name': user.first_name,
        'last_name': user.last_name
    }

homepage/templates/v3/_base.html
{% load render_bundle from webpack_loader %}
{% load static %}
<!DOCTYPE html>
<html lang="nl">
  <head>
    <title>{% if title %}{{ title }} · {% endif %}Atlas · {{ config.ORGANIZATION_NAME }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" >

    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <link rel="shortcut icon" href="{% if config.FAVICON_URL %}{{ config.FAVICON_URL }}{% else %}{% static 'img/favicon.ico' %}{% endif %}" />
</head>
  <body>
    {% block content %}{% endblock %}
    {% render_bundle "app" %}

    {% if google_maps %}
      <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ google_maps.api_key }}"></script>
    {% endif %}

    {% if street_smart %}
      <script type="text/javascript" src="{% static 'vendor/react/16.12.0/react.production.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'vendor/react/16.12.0/react-dom.production.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'vendor/openlayers/4.6.5/ol.js' %}"></script>
      <script type="text/javascript" src="{% static 'vendor/lodash/4.17.15/lodash.min.js' %}"></script>
      <script type="text/javascript" src="https://streetsmart.cyclomedia.com/api/v19.5/StreetSmartApi.js"></script>
    {% endif %}


    {% if config.MATOMO_URL %}
      <script type="text/javascript">
          var _paq = window._paq || [];
          _paq.push(['trackPageView']);
          _paq.push(['enableLinkTracking']);
          (function() {
              var u="{{ config.MATOMO_URL }}/";
              _paq.push(['setTrackerUrl', u+'matomo.php']);
              _paq.push(['setSiteId', {{ config.MATOMO_SITE_ID }}]);
              var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
              g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
          })();
      </script>
    {% endif %}
  </body>
</html>

homepage/templates/v3/admin.html
{% load render_bundle from webpack_loader %}
{% load static %}
<!DOCTYPE html>
<html lang="nl">
  <head>
    <title>Atlas · {{ config.ORGANIZATION_NAME }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" >

    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    <link rel="shortcut icon" href="{% if config.FAVICON_URL %}{{ config.FAVICON_URL }}{% else %}{% static 'img/favicon.ico' %}{% endif %}" />
</head>
  <body>
    <div id="app" class="app"></div>
    {{ data|json_script:"app-data" }}
    {% render_bundle "admin" %}
  </body>
</html>

homepage/templates/v3/app.html
{% extends 'v3/_base.html' %}

{% block content %}
  <div id="app" class="app"></div>
  {{ data|json_script:"app-data" }}
{% endblock %}

homepage/templates/v3/disclaimer.html
{% extends 'v3/_base.html' %}
{% load markdownify %}

{% block content %}
    <div class="content__container">
        <h1>Disclaimer</h1>
        {{ content|linebreaks }}
    </div>
{% endblock %}

homepage/templates/v3/help.html
{% extends 'v3/_base.html' %}
{% load markdownify %}

{% block content %}
    <div class="content__container">
        <h1>Help</h1>
        {{ content | markdown | safe }}
    </div>
{% endblock %}

homepage/templates/v3/login.html
{% extends 'v3/_base.html' %}

{% block content %}
  <div class="login__container">
    {% if AUTHENTICATION_ENABLE_CREDENTIALS %}
      <div class="credentials__container">
        <form method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}">

          <div>
            <div class="login__form-item">
              <label for="id_username">
                Gebruikersnaam
              </label>
              {{ form.username }}
            </div>
            {% for error in form.username.errors %}
                <p>{{ error }}</p>
            {% endfor %}
          </div>

          <div>
            <div class="login__form-item">
              <label for="id_password">
                Wachtwoord
              </label>
              {{ form.password }}
            </div>
            {% for error in form.password.errors %}
                <p>{{ error }}</p>
            {% endfor %}
          </div>

          {{ form.non_field_errors }}

          {% for hidden_field in form.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
          {% endfor %}

          <button type="submit" class="login__submit">Log in</button>
        </form>
      </div>
    {% endif %}

    {% if AUTHENTICATION_ENABLE_OIDC %}
      <div class="sso__container">
        <a href="{% url 'oidc_authentication_init' %}?next={{next}}" class="login__submit">Inloggen via Single Sign On</a>
      </div>
    {% endif %}
  </div>
{% endblock %}

homepage/templates/v3/login_failure.html
{% extends 'v3/_base.html' %}

{% block content %}
  <div class="login__container">
      <div class="credentials__container">
        Het inloggen is mislukt omdat je account (nog) niet geactiveerd is.<br />
        Vraag de beheerder om je account te activeren.
      </div>
      <div class="sso__container">
        <a href="{% url 'homepage:v3' '' %}" class="login__submit">Ga terug</a>
      </div>
  </div>
{% endblock %}